### ISSUE TITLE
К выводу обработанного шаблона добавляется 1

### ISSUE THREAD

**Issue by Qwarble** [MODX-Club/phpTemplates#2]
MODX Revolution 2.2.5-pl (traditional)

phptemplate.class.php
function _process(...)
//Эта конструкция добавляет 1 к выводу
$this->_output = require_once $controller;

**Comment by Fi1osof** [comment]
Добрый день!
Это последствия последнего обновления. Механизм был переработан до более правильного, и теперь контроллер (статический php-шаблон) должен именно возвращать результат, то есть делать return (обычно return $smarty->fetch($tpl); ) А если он не ретурнит, а просто делает принт, то php возвращает просто успех подгрузки файла - 1. Поправьте в контроллерах print на return и все будет ОК.
