### ISSUE TITLE
Предложение.

### ISSUE THREAD

**Issue by Nik-ADA** [MODX-Club/phpTemplates#4]
Столкнулся с трудностью.
На сайте шаблоны стоят как статические. После установки плагина phpTemplates все шаблоны перестали работать.

Предложение можно как-то это исправить в плагине добавить возможно использование таких шаблонов.
добавить в файл phptemplate.class.php что то типа этого  if(empty($this->getProperties($properties))){return;}

хотя думаю что это кривовато

**Comment by rogaldh** [comment]
Речь про то, чтобы статические шаблоны не отрабатывались модулем phpTemplates? Подумаем, как лучше реализовать.

**Comment by Nik-ADA** [comment]
Да совершенно верно.
Я думаю что это будет полезно.

**Comment by Fi1osof** [comment]
Система шаблонизации в MODX улучшилась, и есть Smarty-шаблонизация, потому от phpTemplates вообще уже имеет смысл отказываться.

**Comment by Nik-ADA** [comment]
Это в новой версии что будет, правильно я понял.

**Comment by Fi1osof** [comment]
Да. Я уже попробовал. Достаточно в обычных шаблонах писать [[smarty?tpl=`some.tpl`]](именно кешируемый тег). А уже внутри шаблона что не кешируемое, выводить в отдельные некешируемые элементы. MODX корректно сохранит в кеш именно HTML, а не как раньше исходный [[smarty?tpl=`some.tpl`]]

**Comment by Nik-ADA** [comment]
Николай спасибо за новость :) будем ждать обновление системы.

**Comment by Nik-ADA** [comment]
Николай спасибо за новость :) будем ждать обновление системы.

**Comment by Fi1osof** [comment]
Не за что!

Только уточню на счет системы: речь не о phpTemplates. Речь о самом MODX и отдельном компоненте modxSmarty. Пользоваться этим можно уже вчера. phpTemplates просто стал не актуальным.

**Comment by Nik-ADA** [comment]
modxSmarty знаю, но использовал в связки с phpTemplates. В ШопМодх такая связка была.

**Comment by Fi1osof** [comment]
Да. Вот теперь связка не требуется. Можно просто инклюдить шаблоны сниппетом smarty

**Comment by Nik-ADA** [comment]
Николай есть вопрос, пытаюсь вызвать smarty в шаблоне по вашему примеру [[smarty? tpl="main.tpl"]]

Но выдает ошибку что не может загрузить шаблон.

Вопрос, из какой он папки берет файлы?

**Comment by Fi1osof** [comment]
@Nik-ADA пишите вопрос на сайте Клуба http://modxclub.ru 
Здесь мы подобные обсуждения не ведем.
